services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'orders_db'
    ports:
      - '4000:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      STOCK_PRODUCTS_URL: '${STOCK_PRODUCTS_URL}'
      CUSTOMER_MANAGEMENT_URL: '${CUSTOMER_MANAGEMENT_URL}'
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    restart: always